version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

