export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";

export const QUIZ_ADD_QUESTIONS_REQUEST = "QUIZ_ADD_QUESTIONS_REQUEST";
export const QUIZ_ADD_QUESTIONS_SUCCESS = "QUIZ_ADD_QUESTIONS_SUCCESS";
export const QUIZ_ADD_QUESTIONS_FAIL = "QUIZ_ADD_QUESTIONS_FAIL";

export const QUIZ_ADD_ANS_REQUEST = "QUIZ_ADD_ANS_REQUEST";
export const QUIZ_ADD_ANS_SUCCESS = "QUIZ_ADD_ANS_SUCCESS";
export const QUIZ_ADD_ANS_FAIL = "QUIZ_ADD_ANS_FAIL";

export const QUIZ_DETAILS_REQUEST = "QUIZ_DETAILS_REQUEST";
export const QUIZ_DETAILS_SUCCESS = "QUIZ_DETAILS_SUCCESS";
export const QUIZ_DETAILS_FAIL = "QUIZ_DETAILS_FAIL";

export const QUIZ_REQUEST = "QUIZ_REQUEST";
export const QUIZ_SUCCESS = "QUIZ_SUCCESS";
export const QUIZ_FAIL = "QUIZ_FAIL";

export const GET_QUIZZES_REQUEST = "GET_QUIZZES_REQUEST";
export const GET_QUIZZES_SUCCESS = "GET_QUIZZES_SUCCESS";
export const GET_QUIZZES_FAIL = "GET_QUIZZES_FAIL";

// export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
// export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
// export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";