export const CREATE_TEAM_REQUEST = "CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAIL = "CREATE_TEAM_FAIL";

export const GET_TEAM_REQUEST = "GET_TEAM_REQUEST";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAIL = "GET_TEAM_FAIL";

export const GET_USER_TEAMS_REQUEST = "GET_USER_TEAMS_REQUEST";
export const GET_USER_TEAMS_SUCCESS = "GET_USER_TEAMS_SUCCESS";
export const GET_USER_TEAMS_FAIL = "GET_USER_TEAMS_FAIL";

export const GET_TEAMS_NAME_REQUEST = "GET_TEAMS_NAME_REQUEST";
export const GET_TEAMS_NAME_SUCCESS = "GET_TEAMS_NAME_SUCCESS";
export const GET_TEAMS_NAME_FAIL = "GET_TEAMS_NAME_FAIL";

export const GET_ALL_TEAMS_REQUEST = "GET_ALL_TEAMS_REQUEST";
export const GET_ALL_TEAMS_SUCCESS = "GET_ALL_TEAMS_SUCCESS";
export const GET_ALL_TEAMS_FAIL = "GET_ALL_TEAMS_FAIL";

export const CLEAR_CREATE_TEAM = "CLEAR_CREATE_TEAM";
export const CLEAR_ERRORS = "CLEAR_ERRORS";